name: Slack app deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - name: Install Deno runtime
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno task test

      # - name: Run type check
      #   run: deno check *.ts && deno check **/*.ts && deno check **/**/*.ts

      - name: Install Slack CLI
        if: steps.cache-slack.outputs.cache-hit != 'true'
        run: |
          curl -fsSL https://downloads.slack-edge.com/slack-cli/install.sh | bash

  deploy:
    depends-on: build
    steps:
      - name: Deploy the app
        env:
          SLACK_SERVICE_TOKEN: ${{ secrets.SLACK_SERVICE_TOKEN }}
        run: |
          cd oncall-bot/
          slack deploy -s --token $SLACK_SERVICE_TOKEN
